### ISSUE TITLE
DCS Liberation cannot generate working .miz files past certain commit.

### ISSUE THREAD

**Issue by SnappyComebacks** [pydcs/dcs#140]
When attempting to upgrade DCS Liberation's pydcs version from it's current version: https://github.com/pydcs/dcs/commit/84247a9fa108174b4f9696136a413d53cee23533 to the latest master I discovered that DCS is unable to read/load any .miz when the `liberation_nextturn.miz` is generated using a pydcs version after this commit: https://github.com/pydcs/dcs/commit/e94f697f6c651b82e21dd19e6b221218bda4850f.

In addition, `mission.py` has an error in it on Line `2019` on master.

**Comment by rp-** [comment]
I can hardly believe that this commit has anything todo with this.

but why don't you post the whole stacktrace, or attach the mission which couldn't be loaded?

**Comment by DanAlbert** [comment]
Not OP but was watching in discord while they attempted to diagnose, aiui there isn't a stack trace to post. DCS is the thing failing, and rather unhelpfully. I'll post a link to the thread in a moment when I get to a computer (can't seem to link discord messages from mobile).

I agree with you, none of the patches between where we are and the tip of pydcs master looked particularly likely to cause the problem. Bumping the mission version number seems most likely since that'll (I assume) change how DCS interprets the mission. Also possible that we're putting some garbage in a unit name and that's causing the problem (I haven't seen the mission either), and previously it wasn't an issue because it was getting a translation key instead.

**Comment by DanAlbert** [comment]
Found the mission file in the thread too: [liberation_nextturn.miz.txt](https://github.com/pydcs/dcs/files/6433256/liberation_nextturn.miz.txt)

**Comment by rp-** [comment]
`Error loading mission "C:\Users\peint\Saved Games\DCS\Missions\crash.miz": [string "mission=..."]:1033: '}' expected (to close '{' at line 1026) near 'START'`

line 1033 is:
```
["name"]=RACETRACK START,
```

so waypoint names are incorrectly serialized(stored)

**Comment by rp-** [comment]
I tried a mission just created by pydcs, and this seems to work.
Maybe liberation sets the name wrong currently?
found this in aircraft.py
`            name=self.mission.string(self.waypoint.name),`

**Comment by SnappyComebacks** [comment]
> 
> 
> `Error loading mission "C:\Users\peint\Saved Games\DCS\Missions\crash.miz": [string "mission=..."]:1033: '}' expected (to close '{' at line 1026) near 'START'`
> 
> line 1033 is:
> 
> ```
> ["name"]=RACETRACK START,
> ```
> 
> so waypoint names are incorrectly serialized(stored)

Would you mind sharing how you are getting to this error?  My method is not very good.

**Comment by SnappyComebacks** [comment]
Marched ahead with your earlier suggestion.  Issue appears to be resolved.  See https://github.com/dcs-liberation/dcs_liberation/pull/1063 if interested.

**Comment by rp-** [comment]
> How did you get the pretty error text that you display?

explicitly load the mission in DCS, I mean you have to enter the file name and click open
DCS usually hides files it cannot parse.

**Comment by rp-** [comment]
But maybe a explicit type check on saving would be useful here, to find such errors easier.

**Comment by DanAlbert** [comment]
> But maybe a explicit type check on saving would be useful here, to find such errors easier.

At least until pydcs is mypy clean, that'd probably be a good idea, especially since this is a really hard to find API change from the previous version.

Being mypy clean would be good, but there's a _lot_ to do there.
