### ISSUE TITLE
Position Point to Lat Long?

### ISSUE THREAD

**Issue by JohanAberg** [pydcs/dcs#17]
Hi,
Thanks for this great project.

Is there a way to convert a Mission unit's position to Lat/Long values?
I'd like to plot unit's position on a real map. 
Any ideas or pointers please?

Cheers

**Comment by rp-** [comment]
There is currently no function in the library for that.
But it is possible, I just didn't bother to implement or add an dependency to [pyproj4](https://github.com/pyproj4/pyproj).
With that library it should be fairly easy if we pick the correct projection method,
I think hints for that can be found in the terrian .lua config files in DCS.

**Comment by JohanAberg** [comment]
Great thanks, I'll take a closer look at pyproj.

**Comment by DanAlbert** [comment]
It seems the projection parameters for the Caucasus are available (`Caucasus.MapCoords.lua`), but not for the others. Any idea if that's something that could be extracted from DCS like all the other data? I've poked around a little but haven't found anything so far.

**Comment by rp-** [comment]
No, I have no idea.
I'm afraid this is hidden in the native code somewhere for newer modules

**Comment by DanAlbert** [comment]
I finally got around to finishing this. https://github.com/Khopa/dcs_liberation/commit/8a01209ded308af429e825e48b23e3c1f9138505

@rp- do you want this in pydcs? It would require a dependency on pyproj.

**Comment by rp-** [comment]
I'm fine with that, as a lot of other users could profit from that and don't have to reinvent the wheel themselves

**Comment by DanAlbert** [comment]
Still planning to do this but haven't found the time just yet. There are a few choices in API though that I'd like your thoughts on, @rp-.

The complication is that any point <-> LL conversion is map dependent, so any call to convert needs to know which map is being used.

Using this in Liberation, I added the conversion methods on our Theater object. It's okay, but it does mean plumbing the map information around anywhere we need to convert.

Option 2 (my preference) is to subclass Point into MapPoint which would have the map data and conversion methods. Any cases that don't need conversion could be more cheaply and easily constructed, but we'd still have type safe calls to the conversions.

Is there an option 3? Global state is no good because the API allows multiple missions to exist simultaneously. Precomputing has all the same problems of needing context, but also forces the cost when it's not needed.

**Comment by DanAlbert** [comment]
> From your experience, which Points you don't need to convert?

Pretty much all of them. We need lat/lon to be able to display on a real map, so we do it for waypoints, airbases, unit locations, etc. There are probably a few cases where it doesn't matter because we only constructed the Point for a distance calculation, but anything that isn't transient probably needs a conversion.

I'm _hoping_ (haven't looked to see if it'll actually work out) that most of the points that are created in pydcs itself can actually be `MapPoint`, and that most point constructions are either directly from pydcs or derived from it, so it'd end up mostly transparent to the caller. A lot of our uses are derived from airbase locations or from a loaded miz, and both of those cases already have the map context.

**Comment by rp-** [comment]
Well then, I guess a extra subclass wouldn't help to much, and maybe just add a reference to `Terrain` in the Point class + conversion methods

**Comment by DanAlbert** [comment]
I'll play with it soon and see what I come up with. Thanks for letting me bounce some ideas off you :)

**Comment by DanAlbert** [comment]
This can be closed now :)
