### ISSUE TITLE
Adding MOOSE to generated missions

### ISSUE THREAD

**Issue by jschildt** [pydcs/dcs#33]
Can't figure this out for the life of me, I've tried a couple of approaches using the DoScriptFile() trigger action.

Tried using the full path of my Moose.lua as an argument, tried adding the script to the .miz file via MapResource and then using the key returned as an argument, no joy.

The trigger does show up fine, but the script file field in mission editor is empty. Tried comparing the mission file inside the .miz file for differences when compared against a file from an identical mission made in the ME instead, no major differences there either when it comes to trigger parameters.

Is this just me not doing it right or is it an actual bug/WIP feature?

Trigger code pasted below:

`moose_trigger = TriggerStart(Event.NoEvent, "Moose")
 moose_trigger.add_action(DoScriptFile("E:\\Projects\\lua\\Moose\\Moose.lua"))
 self.mission.triggerrules.triggers.append(moose_trigger)`

**Comment by Khopa** [comment]
I encountered the same issue, so if someone has an answer i'd be interested as well. 

But as a workaround, i decided to use the "DoScript" action instead of the "DoScriptFile", and this one works fine for me. You just have to read the whole file from Python and copy it in the action.

Here is my code, loading another lua framework :

```
       load_mist = TriggerStart(comment="Load Mist Lua Framework")
       with open("./resources/scripts/mist_4_3_74.lua") as f:
           load_mist.add_action(DoScript(String(f.read())))
       self.current_mission.triggerrules.triggers.append(load_mist)
```
[Full source here](https://github.com/shdwp/dcs_liberation/blob/qt_ui/game/operation/operation.py#L196)

Then when i open the mission in the editor, the triggers are correctly generated, and the scripts works as expected:

![image](https://user-images.githubusercontent.com/2546901/82844852-5e4b1d80-9ee2-11ea-9971-865beded06c2.png)

**Comment by jschildt** [comment]
Seems to work fine as a workaround, thank you a thousand for that. Was almost ready to tear my hair out (or what's left of it anyway).

**Comment by rp-** [comment]
I have to admit this is far from easy to understand and needs more "type-safety"(in regards to python), but this sample works for me:

```
    m = dcs.mission.Mission()

    rus = m.country(dcs.countries.Russia.name)
    yak = m.flight_group(rus, "RAT_YAK", dcs.planes.Yak_40, airport=None, position=dcs.Point(0, 0))
    yak.late_activation = True

    mooselua = m.map_resource.add_resource_file("C:\\tmp\\Moose.lua")
    load_trigger = dcs.triggers.TriggerStart()
    load_trigger.actions.append(dcs.action.DoScriptFile(mooselua))
    m.triggerrules.triggers.append(load_trigger)

    rat_trigger = dcs.triggers.TriggerOnce()
    rat_trigger.actions.append(dcs.action.DoScript(m.string('local yak=RAT:New("RAT_YAK")\nyak:Spawn(5)')))
    m.triggerrules.triggers.append(rat_trigger)
```
